package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"github.com/google/uuid"
	"taskManager/graph/model"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, title string, description string) (*model.Task, error) {
		task := &model.Task{
		ID:          uuid.NewString(),
		Title:       title,
		Description: description,
		Done:        false,
	}
	r.Resolver.Tasks = append(r.Resolver.Tasks, task)
	return task, nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, title *string, description *string, done *bool) (*model.Task, error) {
	for _, task := range r.Resolver.Tasks {
		if task.ID == id {
			if title != nil {
				task.Title = *title
			}
			if description != nil {
				task.Description = *description
			}
			if done != nil {
				task.Done = *done
			}
			return task, nil
		}
	}
	return nil, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	for i, task := range r.Resolver.Tasks {
		if task.ID == id {
			r.Resolver.Tasks = append(r.Resolver.Tasks[:i], r.Resolver.Tasks[i+1:]...)
			return true, nil
		}
	}
	return false, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	return r.Resolver.Tasks, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	for _, task := range r.Resolver.Tasks {
		if task.ID == id {
			return task, nil
		}
	}
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
